# Generated by Django 2.1.5 on 2019-02-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_recipie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipies.IngredientType'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='shelf_life',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='photo',
            field=models.ImageField(blank=True, upload_to='recipie_photos'),
        ),
        migrations.AlterField(
            model_name='recipieingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipie_ingredient', to='recipies.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipieingredient',
            name='recipie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipies.Recipie'),
        ),
        migrations.AlterField(
            model_name='recipiestep',
            name='recipie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipies.Recipie'),
        ),
    ]
