# Generated by Django 2.1.5 on 2019-02-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_auto_20190210_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipieingredient',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
