# Generated by Django 2.1.5 on 2019-02-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='name',
            field=models.CharField(default='Misc', max_length=200),
            preserve_default=False,
        ),
    ]
